=== GiraldTec/inmobiliaris-existdb/BDSI_P3/xml/agencias.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Inmobiliarias (Inmobiliaria)*>
<!ELEMENT Inmobiliaria (nombre,direccion?,provincia,localidad?,
                        codigopostal?,telefonos,email,web)>

<!ATTLIST Inmobiliaria  id ID #REQUIRED>

<!ELEMENT nombre (#PCDATA)> 
<!ELEMENT direccion (#PCDATA)> 
<!ELEMENT provincia (#PCDATA)> 
<!ELEMENT localidad (#PCDATA)> 
<!ELEMENT codigopostal (#PCDATA)> 
<!ELEMENT telefonos (telefono)*> 
<!ELEMENT email (#PCDATA)> <!ATTLIST email contacto CDATA #REQUIRED>
<!ELEMENT web (#PCDATA)> 
<!ELEMENT telefono (#PCDATA)> <!ATTLIST telefono  tipo (fijo|movil|fax) #REQUIRED>

=== GiraldTec/inmobiliaris-existdb/BDSI_P3/xml/agencias.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Inmobiliarias SYSTEM "C:\hlocal\trang\agencias.dtd">

<Inmobiliarias>
    <Inmobiliaria id="pitufo">
        <nombre>Pitufos SA</nombre>
        <direccion>C\Pepino 9</direccion>
        <provincia>La Coruña</provincia>
        <localidad>Lugo</localidad>
        <codigopostal>00000</codigopostal>
        <telefonos>
            <telefono tipo = "fijo">5555555</telefono>
            <telefono tipo = "movil">6555555</telefono>
            <telefono tipo = "fax">4555555</telefono>
        </telefonos>
        <email contacto="María Duque">mariad@pitufossa.es</email>
        <web>www.pitufosSM.es</web>
    </Inmobiliaria>
    
    <Inmobiliaria id="gemelos">
        <nombre>Gemelos Malvados SA</nombre>
        <direccion>C\Luisiano 10</direccion>
        <provincia>Madrid</provincia>
        <localidad>Leganes</localidad>
        <codigopostal>33333</codigopostal>
        <telefonos>
            <telefono tipo = "fijo">5111111</telefono>
            <telefono tipo = "fax">4111111</telefono>
        </telefonos>
        <email contacto="Rigoberto Flavio">riflav@gemelosm.es</email>
        <web>www.GemelosMalvados.es</web>
    </Inmobiliaria>
    
    <Inmobiliaria id="infernalia">
        <nombre>Infernalia</nombre>
        <direccion>C\Stigia</direccion>
        <provincia>Barcelona</provincia>
        <localidad>Barna</localidad>
        <codigopostal>22222</codigopostal>
        <telefonos>
            <telefono tipo = "movil">6000666</telefono>
        </telefonos>
        <email contacto="Lucifer Sanchez">lucisan@infernalia.es</email>
        <web>www.infernalia.es</web>
    </Inmobiliaria>
    
    <Inmobiliaria id="inmocasa">
        <nombre>Inmocasa</nombre>
        <direccion>C\Mayor</direccion>
        <provincia>Sevilla</provincia>
        <localidad>Bormujos</localidad>
        <codigopostal>11111</codigopostal>
        <telefonos>
            <telefono tipo = "movil">6000666</telefono>
            <telefono tipo = "fax">7000666</telefono>
            <telefono tipo = "fax">7000665</telefono>
        </telefonos>
        <email contacto="Paco Raban">pacor@inmo.es</email>
        <web>www.infernalia.es</web>
    </Inmobiliaria>
</Inmobiliarias>
