=== GiraldTec/inmobiliaris-existdb/trunk/BDSI_P3/xml/inmuebles.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT inmuebles (anuncio)*>
<!ELEMENT anuncio (inmueble,opcionales,fotos)>
<!ATTLIST anuncio id ID #REQUIRED agencia CDATA #REQUIRED operacion (venta|alquiler) #REQUIRED>
<!ELEMENT inmueble (metros2,provincia,localidad,precio,cp)>
<!ATTLIST inmueble tipo (piso|casa|solar|terreno|local|oficina|almacen|parking|trastero) #REQUIRED
					estado (nuevo|buenEstado|reformado|reformar) #REQUIRED>
<!ELEMENT opcionales (vecinosRuidosos?,numHabs?,piscina?,soleado?,trastero?,baños?,jardin?,calefaccion?)>
<!ELEMENT fotos (foto)*>
<!ELEMENT metros2 (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT vecinosRuidosos (#PCDATA)>
<!ELEMENT calefaccion (#PCDATA)>
<!ELEMENT numHabs (#PCDATA)>
<!ELEMENT piscina (#PCDATA)>
<!ELEMENT soleado (#PCDATA)>
<!ELEMENT trastero (#PCDATA)>
<!ELEMENT baños (#PCDATA)>
<!ELEMENT jardin (#PCDATA)>
<!ELEMENT foto (#PCDATA)>

=== GiraldTec/inmobiliaris-existdb/BDSI_P3/xml/inmuebles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inmuebles SYSTEM "C:\hlocal\trang\inmuebles.dtd">

<inmuebles>
    <anuncio id="piso_01" agencia="infernalia" operacion="venta">
        <inmueble tipo="piso" estado="nuevo">
            <metros2>120</metros2>
           	<provincia>Asturias</provincia>
           	<localidad>Pepinosa</localidad>
        </inmueble>
        
        <opcionales>
            <numHabs>2</numHabs>
            <trastero>Si</trastero>
            <ba単os>3</ba単os>
            <jardin>si</jardin>
        </opcionales>
        <fotos>
            <foto>www.wakawaka.es/foto67.jpg</foto>
        </fotos>
    </anuncio>
    
    <anuncio id="piso_02" agencia="pitufo" operacion="alquiler">
        <inmueble tipo="piso" estado="nuevo">
            <metros2>90</metros2>
           	<provincia>Huesca</provincia>
           	<localidad>Hortalizada</localidad>
        </inmueble>
        
        <opcionales>
        	<calefaccion>si</calefaccion>
            <numHabs>2</numHabs>
            <ba単os>1</ba単os>
        </opcionales>
        <fotos>
            <foto>www.wakawaka.es/foto68.jpg</foto>
        </fotos>
    </anuncio>
    
    <anuncio id="almacen_01" agencia="gemelos" operacion="alquiler">
        <inmueble tipo="almacen" estado="buenEstado">
            <metros2>1000</metros2>
           	<provincia>Alicante</provincia>
           	<localidad>Tomatera</localidad>
        </inmueble>
        <opcionales>
        </opcionales>
        <fotos>
            <foto>www.wakawaka.es/foto69.jpg</foto>
        </fotos>
    </anuncio>
</inmuebles>

=== GiraldTec/inmobiliaris-existdb/trunk/BDSI_P3/xml/inmuebles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inmuebles SYSTEM "C:\hlocal\trang\inmuebles.dtd">

<inmuebles>
    <anuncio id="piso_01" agencia="infernalia" operacion="venta">
        <inmueble tipo="piso" estado="nuevo">
            <metros2>120</metros2>
           	<provincia>Asturias</provincia>
           	<localidad>Pepinosa</localidad>
        </inmueble>
        
        <opcionales>
            <numHabs>2</numHabs>
            <piscina>No</piscina>
            <soleado>No</soleado>
            <trastero>Si</trastero>
            <baños>3</baños>
            <jardin>si</jardin>
        </opcionales>
        <fotos>
            <foto>www.wakawaka.es/foto67.jpg</foto>
        </fotos>
    </anuncio>
</inmuebles>
